### ISSUE TITLE
Deauth::start packet sending

### ISSUE THREAD

**Issue by matrix224** [dj1ch/minigotchi#144]
While playing with the board in #133 I had an issue that was from me choosing the wrong ESP8266 board at first. It resulted in the `Both packets failed to send!` message being printed, which prompted me to go look and see where that was coming from.

It's in the `Deauth::start` method, and after looking over the whole if-else statement setup in the for-loop in there, I was unsure what the intention of all of that is; it didn't seem to make sense.
Is it supposed to try and send both the deauth and disassociation frames, and count it as failed if at least one of those fails?
Or does it just want to try and send at least one of them, and then count it as failed if both fail?

Currently it looks like the latter where it tries to send the deauth or association frame, and if both of those fail, then it counts it as both failing; which is fine. But then all of the else-ifs after about one specific packet failing don't make sense since I imagine they'd most likely never be called (I say most likely because all of the else-ifs try to send the packets again too in their if-statements, which is another thing that seemed odd to me).

**Comment by dj1ch** [comment]
> While playing with the board in https://github.com/dj1ch/minigotchi/issues/133 I had an issue that was from me choosing the wrong ESP8266 board at first. It resulted in the Both packets failed to send! message being printed, which prompted me to go look and see where that was coming from.

Yeah, for some reason any other arduino firmware will not send deauths, I had to use Spacehuhn's boards to compile which allowed for them to actually send them.

> It's in the Deauth::start method, and after looking over the whole if-else statement setup in the for-loop in there, I was unsure what the intention of all of that is; it didn't seem to make sense.
Is it supposed to try and send both the deauth and disassociation frames, and count it as failed if at least one of those fails?
Or does it just want to try and send at least one of them, and then count it as failed if both fail?
Currently it looks like the latter where it tries to send the deauth or association frame, and if both of those fail, then it counts it as both failing; which is fine. But then all of the else-ifs after about one specific packet failing don't make sense since I imagine they'd most likely never be called (I say most likely because all of the else-ifs try to send the packets again too in their if-statements, which is another thing that seemed odd to me).

For debugging purposes I put that down to check whether or not the frame would send. It either returns a `0` or `-1`, and with the normal ESP8266 firmware it would only give me the code `-1`.

It's supposed to send both frames. Something I've learned with authentication is that you'll need to send a deauth and disassoc frame to actually deauth the access point. 

Here are a couple examples of this:

https://github.com/SpacehuhnTech/esp8266_deauther/blob/v2/esp8266_deauther/Attack.cpp#L303
https://github.com/hoangminh5210119/deauther/blob/master/src/Attack.cpp#L337

I have seen projects where they just send the deauth frame, but I haven't tested them thoroughly and people have told me that the deauth packets they send may not be valid.

**Comment by matrix224** [comment]
> For debugging purposes I put that down to check whether or not the frame would send. It either returns a 0 or -1, and with the normal ESP8266 firmware it would only give me the code -1.

Got it


> It's supposed to send both frames. Something I've learned with authentication is that you'll need to send a deauth and disassoc frame to actually deauth the access point.

I was thinking that was the intention, but isn't the code currently not doing that?
i.e.:
```
    if (Deauth::send(deauthFrame, deauthFrameSize, 0) ||
        Deauth::send(disassociateFrame, disassociateFrameSize, 0)) {
```
As long as it sends the deauth frame, the disassociation one won't be sent since it'll just stop the evaluation there. It should be && if you want to always try and send both

**Comment by dj1ch** [comment]
> I was thinking that was the intention, but isn't the code currently not doing that?
i.e.:

```cpp
    if (Deauth::send(deauthFrame, deauthFrameSize, 0) ||
        Deauth::send(disassociateFrame, disassociateFrameSize, 0)) {
```
Thanks for catching that lmao, I'll get that done in a sec.

**Comment by dj1ch** [comment]
Logic error should be fixed now. Thank you
